### ISSUE TITLE
Week0 Individual GitHub pages Review Ticket  Brian Zhang

### ISSUE THREAD

**Issue by BrianZhang2016** [PunarvasuS/TheSlushies#3]
# Brian [Github Pages](https://brianzhang2016.github.io/Brian-Individual/)
- [ ] GitHub page for Test Prep study, requiring 5.1 to 5.2 notes and actions( See "GitHub pages actions" at the bottom of each TPT page on [cspcoders](https://cspcoders.nighthawkcodingsociety.com/)
- [ ] GitHub page that documents Data Structures project, using code snippets for key learnings, and links to  GitHub for code and Replit for runtime
- [ ] GitHub page that documents intended Create Task project for College Board, snippets, and links to Runtime

**Comment by ProRichyMan** [comment]
Grader: Nathan
Under Review: Brian
- [ ] GitHub page for Test Prep study, requiring 5.1 to 5.6 notes and actions( See "GitHub pages actions" at the bottom of each TPT page on [cspcoders](https://cspcoders.nighthawkcodingsociety.com/)
- [ ] GitHub page that documents Data Structures project, using code snippets for key learnings, and links to  GitHub for code and Replit for runtime
- [ ] GitHub page that documents intended Create Task project for College Board, snippets, and links to Runtime
