### ISSUE TITLE
Week 0 Team Review - Derrick Huang

### ISSUE THREAD

**Issue by Pitsco** [PunarvasuS/TheSlushies#5]
Scrum Team GitHub pages (2 points) 
Web Project: 

- [ ] Project Description, Project Plans/Ideas/Wires, Timebox 

- [ ] Team Roles described, Project Owner or Sponsor described, Scrum Board started

Individual Review:

- [ ] GitHub page for Test Prep study, requiring 5.1 to 5.2 notes and actions

- [ ] GitHub page that documents Data Structures project, using code snippets for key learnings, and links to GitHub for code and Replit for runtime

- [ ] GitHub page that documents intended Create Task project for College Board, snippets, and links to Runtime

**Comment by Pitsco** [comment]
Web Project:
Project Description:
![tangible](https://github.com/willcyber/tri3)

**Comment by deimie** [comment]
Individual GitHub pages (3 points)

- [ ] GitHub page for Test Prep study, requiring 5.1, 5.2 notes and actions
[Link to page](https://github.com/Pitsco/derrick_individual/blob/gh-pages/notes.md)

- [ ] GitHub page that documents Data Structures project, using code snippets for key learnings, and links to  GitHub for code and Replit for runtime
[Link to page](https://github.com/Pitsco/derrick_individual/blob/gh-pages/datastructure.md)

- [ ] GitHub page that documents intended Create Task project for College Board, snippets, and links to Runtime
[Link to page](https://github.com/Pitsco/derrick_individual/blob/gh-pages/createtask.md)

`Total Score: 2.75/3`
-.2 for create task idea incomplete
-.05 for menu xmas tree not working completely
