### ISSUE TITLE
Week 0 Review Ticket (Nathan)

### ISSUE THREAD

**Issue by ProRichyMan** [PunarvasuS/TheSlushies#6]
Grader: Byron
Under Review: Nathan
- [x] GitHub page for Test Prep study, requiring 5.1 to 5.2 notes and actions( See "GitHub pages actions" at the bottom of each TPT page on [cspcoders](https://cspcoders.nighthawkcodingsociety.com/)
- [x] GitHub page that documents Data Structures project, using code snippets for key learnings, and links to  GitHub for code and Replit for runtime
- [x] GitHub page that documents intended Create Task project for College Board, snippets, and links to Runtime

**Comment by byronlu06** [comment]
Nathan

- [x] GitHub page for Test Prep study, requiring 5.1 to 5.2 notes and actions( See "GitHub pages actions" at the bottom of each TPT page on [cspcoders](https://cspcoders.nighthawkcodingsociety.com/) 

* Github pages include 5.1 to 5.2 notes from Tech Talk 0

- [x] GitHub page that documents Data Structures project, using code snippets for key learnings, and links to GitHub for code and Replit for runtime

* Github pages links to GitHub for code and Replit runtime with working code

- [x] GitHub page that documents intended Create Task project for College Board, snippets, and links to Runtime

* GitHub pages documents Create Task project for College Board, snippets, and links to Runtime
 
Everything is completed and works (3/3)
